# Generated by Django 3.2.9 on 2021-12-05 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_auto_20211205_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='contry',
            new_name='country',
        ),
    ]
