# Generated by Django 3.2.9 on 2021-12-05 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_rename_contry_order_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additional_info',
        ),
    ]
