# Generated by Django 3.2.9 on 2021-12-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_remove_order_additional_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastname',
        ),
    ]
